### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by b-irb** [jtod/Sigma16#1]
There is a significant lack in documentation which makes understanding the format completely impossible. There is insufficient clarity in regards to the instruction format 

> Each instruction has a 4-bit field called the opcode (op for short). This gives 16 values of the opcode: 14 of them denote the 14 RRR instructions, while two of these values indicate that the instruction is either RX or EXP format, and there is then a secondary opcode in the sb field

Fails to accurately denote the _specific_ format and leaves it to reader interpretation (or to decipher your emulator). Additionally, there is incompleteness in various parts of the documentation:

- full instruction listing and description of behaviour
- linker explanation
- programming guide against the architecture
- how exceptions work within the language

As it stands, currently deriving architectural information from the emulator is error prone and tedious (not to mention references to seemingly architectural components which are not present in the official documentation). 

Providing comprehensive documentation would significantly benefit the architecture overall by formalising aspects of it. Most desired additions would be: full instruction format, full instruction behaviour (including exceptions), how memory is handled, more in-depth explanations of the object files (if they are standardised), then a user programming guide.

**Comment by jtod** [comment]
Thanks for your comments.  I've added a note to the README indicating that (1) this is a pre-release of a Version 3, which is a complete rewrite of the system, and all the code and documentation are being revised; expected completion in February 2010. (2) Previous major versions (0, 1, 2) do have very extensive documentation but only in a protected Moodle server, but as those versions are obsolete they won't be made available on github.
